### ISSUE TITLE
spaCy model fr_core_web_md does not exist

### ISSUE THREAD

**Issue by AnnaBobasheva** [twktheainur/pyclinrec#2]
In intersection_recognizers.py there is a statement 

https://github.com/twktheainur/pyclinrec/blob/1cdb33e3e181fcff44ffd217b70d08dbad63a499/pyclinrec/recognizer/intersection_recognizers.py#L47

47            import fr_core_web_md
48            self.spacy = fr_core_web_md.load()

The model fr_core_web_md does not exist rather there are 4 other  [models  ](https://spacy.io/models/fr). I assume that a most suitable model would be fr_core_news_md

**Comment by twktheainur** [comment]
Yes, agreed, fix pushed
