### ISSUE TITLE
Cache object is referenced before it was initialized.

### ISSUE THREAD

**Issue by AnnaBobasheva** [twktheainur/pyclinrec#3]
[/usr/local/lib/python3.7/dist-packages/pyclinrec/utils/sparql.py](https://localhost:8080/#) in _fetch_from_cache_or_query(self, query)
     86             if len(result) == 0:
     87                 result = ""
---> 88             self.redis.set(cache_key, result)
     89         strres = str(result, 'utf-8')
     90         return json.loads(strres)

AttributeError: 'NoneType' object has no attribute 'set'

In my branch  I just checked if redis object is not null but in general I think it would be better to instantiate it in _fetch_from_cache_or_query method.

**Comment by twktheainur** [comment]
Actually, the redis object should be passed in the instantiation of SparQLOffsetFetcher, if it's not passed it should be None by default and if it's None. 
The bug is the absence of the check for self.redis is not None before the set operation. 

Pushed a fix.
