### ISSUE TITLE
SPARQL issue

### ISSUE THREAD

**Issue by AnnaBobasheva** [twktheainur/pyclinrec#5]
The count variable in SELECT clause has to be enclosed in parentheses, otherwise, some parsers return a syntax error. For example, dockerized Virtuoso.

https://github.com/twktheainur/pyclinrec/blob/1cdb33e3e181fcff44ffd217b70d08dbad63a499/pyclinrec/utils/sparql.py#L34

the line should read:
query = f"""define sql:big-data-const 0\n {self.prefixes}\n SELECT (count(distinct *) as ?count) \nFROM <{self.from_statement}> WHERE {{

**Comment by twktheainur** [comment]
I accepted your pull request with the fix
